name: Build and Test

on:
  pull_request:
    branches:
      - next

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v3
        with:
          version: 8.12.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Run tests
        run: |
          pnpm test:packages --changedSince=origin/next --ci --json --coverage --testLocationInResults --outputFile=report.json

      - name: Coverage
        uses: artiomtr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: report.json
          base-coverage-file: report.json
          threshold: 80

      - name: Build
        run: pnpm build:agent
